</main>
<footer class="ruwa-footer">
  <div class="ruwa-shell ruwa-footer-grid">
    <section class="ruwa-footer-brand">
      <a class="ruwa-brand ruwa-brand-light" href="<?php echo esc_url(home_url('/')); ?>"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M20 4c7 8 11 14 11 21a11 11 0 1 1-22 0c0-7 4-13 11-21Z"/><path d="M13 27c5-2 10-6 14-12"/></svg><strong>RUWA BEAUTY</strong></a>
      <p><?php esc_html_e('Purposeful skincare designed to make cleansing, treatment, hydration and protection feel beautifully simple.', 'nub-ruwah'); ?></p>
      <div class="ruwa-socials"><a href="#" aria-label="Instagram">Instagram</a><a href="#" aria-label="TikTok">TikTok</a></div>
    </section>
    <section><h3><?php esc_html_e('Shop', 'nub-ruwah'); ?></h3><a href="<?php echo esc_url(ruwa_shop_url()); ?>"><?php esc_html_e('Shop All', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(add_query_arg('orderby','date',ruwa_shop_url())); ?>"><?php esc_html_e('New Arrivals', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(add_query_arg('orderby','popularity',ruwa_shop_url())); ?>"><?php esc_html_e('Best Sellers', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url('bundles')); ?>"><?php esc_html_e('Ritual Sets', 'nub-ruwah'); ?></a></section>
    <section><h3><?php esc_html_e('Customer Care', 'nub-ruwah'); ?></h3><a href="<?php echo esc_url(ruwa_page_url_any(['contact','contact-us'])); ?>"><?php esc_html_e('Contact Us', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url_any(['faq','faqs'])); ?>"><?php esc_html_e('FAQs', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url_any(['shipping-delivery','shipping-policy'])); ?>"><?php esc_html_e('Shipping & Delivery', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url_any(['returns-refunds','return-policy'])); ?>"><?php esc_html_e('Returns & Refunds', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url('track-order')); ?>"><?php esc_html_e('Track Order', 'nub-ruwah'); ?></a></section>
    <section><h3><?php esc_html_e('Explore', 'nub-ruwah'); ?></h3><a href="<?php echo esc_url(ruwa_page_url_any(['story','about-us'])); ?>"><?php esc_html_e('Our Story', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url('skin-care')); ?>"><?php esc_html_e('Skin Care', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url_any(['blog','beauty-guide'])); ?>"><?php esc_html_e('Glow Guide', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url_any(['quality-safety','quality-testing'])); ?>"><?php esc_html_e('Quality & Safety', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url('privacy-policy')); ?>"><?php esc_html_e('Privacy Policy', 'nub-ruwah'); ?></a><a href="<?php echo esc_url(ruwa_page_url_any(['terms-conditions','terms-and-conditions'])); ?>"><?php esc_html_e('Terms & Conditions', 'nub-ruwah'); ?></a></section>
  </div>
  <div class="ruwa-shell">
    <section class="ruwa-support"><div><span class="ruwa-eyebrow ruwa-eyebrow-dark"><?php esc_html_e('NEED A LITTLE HELP?', 'nub-ruwah'); ?></span><h2><?php esc_html_e('Our support team is here for you.', 'nub-ruwah'); ?></h2></div><div class="ruwa-support-cards"><a href="mailto:support@ruwahbeauty.com"><i>✉</i><small><?php esc_html_e('EMAIL US', 'nub-ruwah'); ?></small><strong>support@ruwahbeauty.com</strong></a><a href="<?php echo esc_url(ruwa_page_url_any(['contact','contact-us'])); ?>"><i>◉</i><small><?php esc_html_e('SUPPORT', 'nub-ruwah'); ?></small><strong><?php esc_html_e('Contact RUWA', 'nub-ruwah'); ?></strong></a></div></section>
  </div>
  <div class="ruwa-footer-bottom"><div class="ruwa-shell"><span>© <?php echo esc_html(gmdate('Y')); ?> RUWA BEAUTY</span><span><?php esc_html_e('SECURE CHECKOUT · CUSTOMER CARE', 'nub-ruwah'); ?></span></div></div>
</footer>
<?php wp_footer(); ?>
</body></html>