</main>
<footer class="ruwa-footer">
  <div class="ruwa-shell ruwa-footer-grid">
    <section class="ruwa-footer-brand"><a class="ruwa-brand ruwa-brand-light" href="<?php echo esc_url(home_url('/')); ?>"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3c5 6 8 10 8 15a8 8 0 1 1-16 0c0-5 3-9 8-15Z"/><path d="M11 20c3-1 6-3 10-7"/></svg><strong>RUWA BEAUTY</strong></a><p>Purposeful skincare crafted to make cleansing, treatment, hydration and protection feel beautifully simple.</p></section>
    <section><h3>Shop</h3><a href="<?php echo esc_url(ruwa_shop_url()); ?>">Shop All</a><a href="<?php echo esc_url(ruwa_shop_url()); ?>?orderby=date">New Arrivals</a><a href="<?php echo esc_url(ruwa_shop_url()); ?>?orderby=popularity">Best Sellers</a><a href="<?php echo esc_url(ruwa_page_url('bundles')); ?>">Bundles</a></section>
    <section><h3>Customer Care</h3><a href="<?php echo esc_url(ruwa_page_url('contact')); ?>">Contact Us</a><a href="<?php echo esc_url(ruwa_page_url('faq')); ?>">FAQs</a><a href="<?php echo esc_url(ruwa_page_url('shipping-delivery')); ?>">Shipping & Delivery</a><a href="<?php echo esc_url(ruwa_page_url('returns-refunds')); ?>">Returns & Refunds</a><a href="<?php echo esc_url(ruwa_page_url('track-order')); ?>">Track Order</a></section>
    <section><h3>Explore</h3><a href="<?php echo esc_url(ruwa_page_url('story')); ?>">Our Story</a><a href="<?php echo esc_url(ruwa_page_url('skin-care')); ?>">Skin Care</a><a href="<?php echo esc_url(ruwa_page_url('glow-guide')); ?>">Glow Guide</a><a href="<?php echo esc_url(ruwa_page_url('quality-safety')); ?>">Quality & Safety</a><a href="<?php echo esc_url(ruwa_page_url('privacy-policy')); ?>">Privacy Policy</a><a href="<?php echo esc_url(ruwa_page_url('terms-conditions')); ?>">Terms & Conditions</a></section>
  </div>
  <div class="ruwa-shell"><section class="ruwa-support"><div><span class="ruwa-eyebrow ruwa-eyebrow-dark">NEED A LITTLE HELP?</span><h2>Our support team is <em>here for you.</em></h2></div><div class="ruwa-support-cards"><a href="mailto:support@ruwahbeauty.com"><i>✉</i><small>EMAIL US</small><strong>support@ruwahbeauty.com</strong></a><a href="https://wa.me/" target="_blank" rel="noopener"><i>◉</i><small>WHATSAPP</small><strong>WhatsApp Support</strong></a></div></section></div>
  <div class="ruwa-footer-bottom"><div class="ruwa-shell"><span>© <?php echo esc_html(gmdate('Y')); ?> RUWA BEAUTY</span><span>VISA · MASTERCARD · SECURE CHECKOUT</span></div></div>
</footer>
<?php wp_footer(); ?>
</body></html>