document.addEventListener('DOMContentLoaded',()=>{
  const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const menu=document.querySelector('.rb-menu');
  const nav=document.querySelector('.rb-nav');
  if(menu&&nav){const close=()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open')};menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',close));document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
  const normalize=u=>{try{const x=new URL(u,location.origin);return x.pathname.replace(/\/$/,'')||'/'}catch(e){return u}};
  const current=normalize(location.href);document.querySelectorAll('.rb-nav a').forEach(link=>{if(normalize(link.href)===current){link.classList.add('is-active');link.setAttribute('aria-current','page')}});
  const header=document.querySelector('.rb-header');const updateHeader=()=>header&&header.classList.toggle('scrolled',window.scrollY>18);updateHeader();addEventListener('scroll',updateHeader,{passive:true});
  document.querySelectorAll('.rb-faq h2,.rb-faq h3').forEach((heading,index)=>{const panel=heading.nextElementSibling;if(!panel)return;panel.classList.add('rb-accordion-panel');const id=`rb-faq-panel-${index}`;panel.id=id;heading.setAttribute('role','button');heading.setAttribute('tabindex','0');heading.setAttribute('aria-controls',id);heading.setAttribute('aria-expanded','false');const toggle=()=>{const open=heading.getAttribute('aria-expanded')==='true';heading.setAttribute('aria-expanded',String(!open));heading.classList.toggle('is-open',!open);panel.classList.toggle('is-open',!open);panel.style.maxHeight=!open?`${panel.scrollHeight+32}px`:'0px'};heading.addEventListener('click',toggle);heading.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})});
  if(!reduce&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.rb-reveal').forEach(el=>observer.observe(el))}else document.querySelectorAll('.rb-reveal').forEach(el=>el.classList.add('is-visible'));
  const parallax=document.querySelector('.rb-parallax');if(parallax&&!reduce&&matchMedia('(min-width: 901px)').matches)addEventListener('scroll',()=>{parallax.style.transform=`translate3d(0,${Math.min(scrollY*.05,28)}px,0)`},{passive:true});
});
