<style id="ruwah-newsletter-footer-palette">
:root{--rb-community-purple:#7B2BAF;--rb-community-white:#F8F4FF;--rb-community-soft:#F1E8F8}
.home .rb-newsletter,.rb-newsletter{background:#7B2BAF!important;background-image:none!important;color:#F8F4FF!important}
.home .rb-newsletter .rb-kicker,.rb-newsletter .rb-kicker{color:#F1E8F8!important}
.home .rb-newsletter h2,.rb-newsletter h2,.home .rb-newsletter p,.rb-newsletter p{color:#F8F4FF!important}
.home .rb-newsletter input[type="email"],.rb-newsletter input[type="email"]{background:#fff!important;color:#24152f!important;border:1px solid rgba(255,255,255,.7)!important}
.home .rb-newsletter input[type="email"]::placeholder,.rb-newsletter input[type="email"]::placeholder{color:#76657f!important;opacity:1!important}
.home .rb-newsletter .rb-button,.rb-newsletter .rb-button{background:#fff!important;color:#7B2BAF!important;border-color:#fff!important}
.home .rb-newsletter .rb-button:hover,.rb-newsletter .rb-button:hover{background:#F1E8F8!important;color:#65218f!important;border-color:#F1E8F8!important}
.rb-footer{background:#7B2BAF!important;background-image:none!important;color:#F8F4FF!important}
.rb-footer .rb-brand,.rb-footer .rb-brand strong,.rb-footer h3,.rb-footer p,.rb-footer span{color:#F8F4FF!important}
.rb-footer a{color:#F1E8F8!important}
.rb-footer a:hover,.rb-footer a:focus-visible{color:#fff!important}
.rb-footer-bottom{border-color:rgba(248,244,255,.28)!important;color:#F8F4FF!important}
</style>
</main><footer class="rb-footer"><div class="rb-shell rb-footer-grid"><section><a class="rb-brand" href="<?php echo esc_url(home_url('/')); ?>"><strong>RUWAH BEAUTY</strong></a><p>Purposeful skincare for simple, confident everyday routines.</p></section><section><h3>Shop</h3><a href="<?php echo esc_url(ruwah_shop_url()); ?>">Shop All</a><a href="<?php echo esc_url(add_query_arg('orderby','date',ruwah_shop_url())); ?>">New Arrivals</a><a href="<?php echo esc_url(add_query_arg('orderby','popularity',ruwah_shop_url())); ?>">Bestsellers</a><a href="<?php echo esc_url(ruwah_page_url('bundles')); ?>">Bundles</a></section><section><h3>Customer Care</h3><a href="<?php echo esc_url(ruwah_page_url('contact')); ?>">Contact</a><a href="<?php echo esc_url(ruwah_page_url('faqs')); ?>">FAQs</a><a href="<?php echo esc_url(ruwah_page_url('shipping-delivery')); ?>">Shipping</a><a href="<?php echo esc_url(ruwah_page_url('track-order')); ?>">Track Order</a></section><section><h3>Explore</h3><a href="<?php echo esc_url(ruwah_page_url('our-story')); ?>">Our Story</a><a href="<?php echo esc_url(ruwah_page_url('quality-testing')); ?>">Quality & Testing</a><a href="<?php echo esc_url(ruwah_page_url('beauty-guide')); ?>">Beauty Guide</a><a href="<?php echo esc_url(ruwah_page_url('privacy-policy')); ?>">Privacy</a></section></div><div class="rb-shell rb-footer-bottom"><span>© <?php echo esc_html(gmdate('Y')); ?> Ruwah Beauty</span><span>Secure checkout · Pakistan-wide delivery</span></div></footer><nav class="rb-mobile-nav"><a href="<?php echo esc_url(home_url('/')); ?>">⌂<span>Home</span></a><a href="<?php echo esc_url(ruwah_shop_url()); ?>">◇<span>Shop</span></a><button data-search-open>⌕<span>Search</span></button><a href="<?php echo esc_url(ruwah_account_url()); ?>">◎<span>Account</span></a><button data-cart-open>▢<span>Bag</span></button></nav><?php wp_footer(); ?></body></html>