<style id="ruwah-newsletter-footer-palette">
:root{--rb-community-purple:#7B2BAF;--rb-community-purple-dark:#65218F;--rb-community-white:#F8F4FF;--rb-community-soft:#F1E8F8}
.home .rb-newsletter,.rb-newsletter{background:#7B2BAF!important;background-image:none!important;color:#F8F4FF!important}
.home .rb-newsletter .rb-kicker,.rb-newsletter .rb-kicker{color:#F1E8F8!important}
.home .rb-newsletter h2,.rb-newsletter h2,.home .rb-newsletter p,.rb-newsletter p{color:#F8F4FF!important}
.home .rb-newsletter input[type="email"],.rb-newsletter input[type="email"]{background:#fff!important;color:#24152f!important;border:1px solid rgba(255,255,255,.7)!important}
.home .rb-newsletter input[type="email"]::placeholder,.rb-newsletter input[type="email"]::placeholder{color:#76657f!important;opacity:1!important}
.home .rb-newsletter .rb-button,.rb-newsletter .rb-button{background:#fff!important;color:#7B2BAF!important;border-color:#fff!important}
.home .rb-newsletter .rb-button:hover,.rb-newsletter .rb-button:hover{background:#F1E8F8!important;color:#65218f!important;border-color:#F1E8F8!important}
body .rb-footer{padding:48px 0 18px!important;background:#7B2BAF!important;background-image:linear-gradient(135deg,#7B2BAF 0%,#7B2BAF 72%,#65218F 100%)!important;color:#F8F4FF!important;border-top:1px solid rgba(255,255,255,.18)!important}
body .rb-footer .rb-shell,body .rb-footer .rb-footer-grid,body .rb-footer .rb-footer-bottom,body .rb-footer section{background:transparent!important;background-image:none!important}
body .rb-footer .rb-footer-grid{gap:34px!important}
body .rb-footer .rb-brand,body .rb-footer .rb-brand strong,body .rb-footer h3,body .rb-footer p,body .rb-footer span{color:#F8F4FF!important}
body .rb-footer a{color:#F1E8F8!important;margin:6px 0!important}
body .rb-footer a:hover,body .rb-footer a:focus-visible{color:#fff!important}
body .rb-footer-bottom{margin-top:28px!important;padding-top:16px!important;border-color:rgba(248,244,255,.30)!important;color:#F8F4FF!important}
.rb-product-actions .button,.rb-product-actions .add_to_cart_button{background:#7B2BAF!important;color:#fff!important;border-color:#7B2BAF!important}
.rb-product-actions .button:hover,.rb-product-actions .button:focus-visible,.rb-product-actions .add_to_cart_button:hover,.rb-product-actions .add_to_cart_button:focus-visible{background:#65218F!important;color:#fff!important;border-color:#65218F!important;box-shadow:0 8px 20px rgba(123,43,175,.24)!important}
</style>
<style id="ruwah-transparent-hero-product">
.home .rb-hero-media{position:absolute!important;isolation:isolate!important;overflow:hidden!important;background:radial-gradient(circle at 53% 42%,rgba(255,255,255,.92) 0 13%,rgba(255,255,255,.54) 30%,rgba(255,255,255,0) 57%),linear-gradient(145deg,#f9f6fd 0%,#eee3f8 46%,#d9c2ee 100%)!important}
.home .rb-hero-media>img{opacity:0!important;visibility:hidden!important}
.home .rb-hero-media:before{content:""!important;position:absolute!important;inset:9% 8% 8%!important;width:auto!important;height:auto!important;border-radius:48% 48% 18% 18%!important;background:linear-gradient(155deg,rgba(255,255,255,.64),rgba(255,255,255,.12))!important;border:1px solid rgba(255,255,255,.72)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.8),0 28px 70px rgba(71,35,101,.13)!important;transform:none!important}
.home .rb-hero-media:after{content:""!important;position:absolute!important;z-index:3!important;inset:5% 7% 3% 5%!important;background:url('<?php echo esc_url(get_template_directory_uri().'/assets/hero-product.php?v=1'); ?>') center bottom/contain no-repeat!important;filter:drop-shadow(0 30px 26px rgba(71,35,101,.24))!important;pointer-events:none!important}
@media(max-width:760px){.home .rb-hero-media{background:radial-gradient(circle at 50% 35%,rgba(255,255,255,.9),rgba(255,255,255,0) 58%),linear-gradient(180deg,#f4edf9,#dcc7ef)!important}.home .rb-hero-media:before{inset:5% 10% 7%!important;border-radius:42% 42% 16% 16%!important}.home .rb-hero-media:after{inset:2% 11% 1%!important}}
</style>
</main><footer class="rb-footer"><div class="rb-shell rb-footer-grid"><section><a class="rb-brand" href="<?php echo esc_url(home_url('/')); ?>"><strong>RUWAH BEAUTY</strong></a><p>Purposeful skincare for simple, confident everyday routines.</p></section><section><h3>Shop</h3><a href="<?php echo esc_url(ruwah_shop_url()); ?>">Shop All</a><a href="<?php echo esc_url(add_query_arg('orderby','date',ruwah_shop_url())); ?>">New Arrivals</a><a href="<?php echo esc_url(add_query_arg('orderby','popularity',ruwah_shop_url())); ?>">Bestsellers</a><a href="<?php echo esc_url(ruwah_page_url('bundles')); ?>">Bundles</a></section><section><h3>Customer Care</h3><a href="<?php echo esc_url(ruwah_page_url('contact')); ?>">Contact</a><a href="<?php echo esc_url(ruwah_page_url('faqs')); ?>">FAQs</a><a href="<?php echo esc_url(ruwah_page_url('shipping-delivery')); ?>">Shipping</a><a href="<?php echo esc_url(ruwah_page_url('track-order')); ?>">Track Order</a></section><section><h3>Explore</h3><a href="<?php echo esc_url(ruwah_page_url('our-story')); ?>">Our Story</a><a href="<?php echo esc_url(ruwah_page_url('quality-testing')); ?>">Quality & Testing</a><a href="<?php echo esc_url(ruwah_page_url('beauty-guide')); ?>">Beauty Guide</a><a href="<?php echo esc_url(ruwah_page_url('privacy-policy')); ?>">Privacy</a></section></div><div class="rb-shell rb-footer-bottom"><span>© <?php echo esc_html(gmdate('Y')); ?> Ruwah Beauty</span><span>Secure checkout · Pakistan-wide delivery</span></div></footer><nav class="rb-mobile-nav"><a href="<?php echo esc_url(home_url('/')); ?>">⌂<span>Home</span></a><a href="<?php echo esc_url(ruwah_shop_url()); ?>">◇<span>Shop</span></a><button data-search-open>⌕<span>Search</span></button><a href="<?php echo esc_url(ruwah_account_url()); ?>">◎<span>Account</span></a><button data-cart-open>▢<span>Bag</span></button></nav><?php wp_footer(); ?></body></html>