<?php
defined('ABSPATH') || exit;
get_header();
$products = ruwah_products(8);
$featured = ruwah_featured_product();
$categories = function_exists('get_terms') ? get_terms(['taxonomy'=>'product_cat','hide_empty'=>true,'number'=>5,'exclude'=>[get_option('default_product_cat')]]) : [];
$posts = get_posts(['post_type'=>'post','post_status'=>'publish','posts_per_page'=>3,'no_found_rows'=>true]);
$concerns = ['Acne & Breakouts','Pigmentation','Dryness','Dullness','Fine Lines','Sensitive Skin'];
$ingredients = [['Niacinamide','Tone, clarity and barrier support'],['Hyaluronic Acid','Comforting hydration'],['Vitamin C','Brightness and antioxidant care'],['Retinol','Night-time renewal']];
?>
<section class="rb-hero"><div class="rb-shell rb-hero-copy"><div class="rb-hero-content"><span class="rb-kicker">SKINCARE, CONSIDERED</span><h1>Thoughtful skincare for confidently cared-for skin.</h1><p>Simple, purposeful formulas designed to cleanse, treat, hydrate and protect—without making skincare feel complicated.</p><div class="rb-actions"><a class="rb-button" href="<?php echo esc_url(add_query_arg('orderby','popularity',ruwah_shop_url())); ?>">Shop Bestsellers</a><a class="rb-button rb-button--light" href="#routine">Find Your Routine</a></div><div class="rb-proof"><span>Authentic products</span><span>Secure checkout</span><span>Customer support</span></div></div></div><div class="rb-hero-media" aria-hidden="true"><div class="rb-hero-frame"><span class="rb-hero-note">DAILY RITUAL</span><?php if($featured) echo wp_kses_post($featured->get_image('full',['loading'=>'eager','decoding'=>'async'])); ?></div></div></section>
<?php if(!is_wp_error($categories)&&$categories): ?><section class="rb-section rb-category-section rb-reveal"><div class="rb-shell"><header class="rb-section-head rb-section-head--split"><div><span class="rb-kicker">SHOP THE RITUAL</span><h2>Build a routine that feels easy.</h2></div><a class="rb-text-link" href="<?php echo esc_url(ruwah_shop_url()); ?>">View all categories</a></header><div class="rb-category-grid"><?php foreach($categories as $cat): $thumb=(int)get_term_meta($cat->term_id,'thumbnail_id',true); ?><a class="rb-category-card" href="<?php echo esc_url(get_term_link($cat)); ?>"><span class="rb-category-media"><?php echo $thumb?wp_get_attachment_image($thumb,'woocommerce_thumbnail',false,['loading'=>'lazy','decoding'=>'async']):'<i>◇</i>'; ?></span><strong><?php echo esc_html($cat->name); ?></strong><small>Explore collection</small></a><?php endforeach; ?></div></div></section><?php endif; ?>
<?php if($products): ?><section class="rb-section rb-section--soft" id="new"><div class="rb-shell"><header class="rb-section-head rb-section-head--split rb-reveal"><div><span class="rb-kicker">FRESHLY ADDED</span><h2>New arrivals.</h2></div><a class="rb-text-link" href="<?php echo esc_url(add_query_arg('orderby','date',ruwah_shop_url())); ?>">Shop all products</a></header><div class="rb-product-grid"><?php foreach($products as $product) ruwah_product_card($product,'New'); ?></div></div></section><?php endif; ?>
<section class="rb-section" id="routine"><div class="rb-shell rb-routine-layout rb-reveal"><article class="rb-routine-primary"><span class="rb-kicker rb-kicker--light">PERSONALISED CARE</span><h2>Build a routine around your skin.</h2><p>Start with what matters most today. Choose a concern and browse a focused collection without overcomplicating your shelf.</p><div class="rb-routine-steps"><div><span>01</span><strong>Know your skin</strong></div><div><span>02</span><strong>Choose a concern</strong></div><div><span>03</span><strong>Build your ritual</strong></div></div><div class="rb-routine-links"><a href="<?php echo esc_url(add_query_arg('s','Dryness',ruwah_shop_url())); ?>">Dryness</a><a href="<?php echo esc_url(add_query_arg('s','Pigmentation',ruwah_shop_url())); ?>">Pigmentation</a><a href="<?php echo esc_url(add_query_arg('s','Acne',ruwah_shop_url())); ?>">Breakouts</a></div></article><article class="rb-routine-secondary"><span class="rb-kicker">BETTER TOGETHER</span><h3>Complete routines, considered as one.</h3><p>Discover curated bundles designed to work together while keeping your routine simple.</p><a class="rb-text-link" href="<?php echo esc_url(ruwah_page_url('bundles')); ?>">Explore bundles</a></article></div></section>
<section class="rb-section rb-section--soft" id="concerns"><div class="rb-shell"><header class="rb-section-head rb-reveal"><span class="rb-kicker">SHOP BY CONCERN</span><h2>Care focused on what matters to you.</h2></header><div class="rb-concern-layout rb-reveal"><?php foreach(array_slice($concerns,0,3) as $index=>$concern): ?><a class="rb-concern-card rb-concern-card--<?php echo esc_attr((string)($index+1)); ?>" href="<?php echo esc_url(add_query_arg('s',$concern,ruwah_shop_url())); ?>"><span class="rb-kicker">EXPLORE CARE</span><strong><?php echo esc_html($concern); ?></strong><i>↗</i></a><?php endforeach; ?></div><div class="rb-concern-links"><?php foreach(array_slice($concerns,3) as $concern): ?><a href="<?php echo esc_url(add_query_arg('s',$concern,ruwah_shop_url())); ?>"><span><?php echo esc_html($concern); ?></span><b>→</b></a><?php endforeach; ?></div></div></section>
<?php if($featured): $rating=(float)$featured->get_average_rating();$count=(int)$featured->get_review_count(); ?><section class="rb-section"><div class="rb-shell rb-feature rb-reveal"><div class="rb-feature-media"><span class="rb-feature-label">BESTSELLER</span><?php echo wp_kses_post($featured->get_image('full',['loading'=>'lazy','decoding'=>'async'])); ?></div><div class="rb-feature-copy"><span class="rb-kicker">MOST LOVED</span><h2><?php echo esc_html($featured->get_name()); ?></h2><?php if($count>0): $f=max(0,min(5,(int)round($rating))); ?><div class="rb-card-rating"><span><?php echo esc_html(str_repeat('★',$f).str_repeat('☆',5-$f)); ?></span><span class="rb-rating-count"><?php echo esc_html(number_format_i18n($rating,1).' · '.$count.' reviews'); ?></span></div><?php endif; ?><p><?php echo wp_kses_post(wp_trim_words($featured->get_short_description()?:$featured->get_description(),32)); ?></p><div class="rb-price"><?php echo wp_kses_post($featured->get_price_html()); ?></div><ul class="rb-feature-benefits"><li>Authentic Ruwah Beauty product</li><li>Secure checkout</li><li>Pakistan-wide delivery</li></ul><div class="rb-actions"><?php if($featured->is_purchasable()&&$featured->is_in_stock()): ?><a rel="nofollow" data-product_id="<?php echo esc_attr((string)$featured->get_id()); ?>" data-quantity="1" class="rb-button add_to_cart_button ajax_add_to_cart" href="<?php echo esc_url($featured->add_to_cart_url()); ?>">Add to Bag</a><?php endif; ?><a class="rb-text-link" href="<?php echo esc_url($featured->get_permalink()); ?>">View Product</a></div></div></div></section><?php endif; ?>
<section class="rb-trust-section"><div class="rb-shell rb-trust rb-reveal"><div><i>✓</i><span><b>Authentic products</b><small>Original Ruwah formulas</small></span></div><div><i>◇</i><span><b>Quality focused</b><small>Clear product information</small></span></div><div><i>⌁</i><span><b>Secure checkout</b><small>Protected payment experience</small></span></div><div><i>→</i><span><b>Pakistan-wide</b><small>Delivery across Pakistan</small></span></div></div></section>
<section class="rb-section"><div class="rb-shell rb-ingredient-layout"><div class="rb-ingredient-intro rb-reveal"><span class="rb-kicker">INGREDIENT INDEX</span><h2>Ingredients worth knowing.</h2><p>Clear, useful guidance to help you explore formulas by the ingredient you are looking for.</p></div><a class="rb-ingredient-feature rb-reveal" href="<?php echo esc_url(add_query_arg('s',$ingredients[0][0],ruwah_shop_url())); ?>"><span>01</span><div><span class="rb-kicker rb-kicker--light">EXPLORE FORMULAS</span><strong><?php echo esc_html($ingredients[0][0]); ?></strong><p><?php echo esc_html($ingredients[0][1]); ?></p></div><i>↗</i></a><div class="rb-ingredient-list rb-reveal"><?php foreach(array_slice($ingredients,1) as $index=>$ingredient): ?><a href="<?php echo esc_url(add_query_arg('s',$ingredient[0],ruwah_shop_url())); ?>"><span>0<?php echo esc_html((string)($index+2)); ?></span><strong><?php echo esc_html($ingredient[0]); ?></strong><em><?php echo esc_html($ingredient[1]); ?></em><b>→</b></a><?php endforeach; ?></div></div></section>
<?php if($posts): ?><section class="rb-section rb-section--soft" id="guide"><div class="rb-shell"><header class="rb-section-head rb-section-head--split rb-reveal"><div><span class="rb-kicker">THE GLOW GUIDE</span><h2>Skincare, explained simply.</h2></div><a class="rb-text-link" href="<?php echo esc_url(ruwah_page_url('blog')); ?>">Read all articles</a></header><div class="rb-guide-grid"><?php foreach($posts as $post_item): ?><article class="rb-guide-card rb-reveal"><a class="rb-guide-media" href="<?php echo esc_url(get_permalink($post_item)); ?>"><?php echo get_the_post_thumbnail($post_item,'large',['loading'=>'lazy','decoding'=>'async']); ?></a><span class="rb-kicker"><?php echo esc_html(get_the_date('',$post_item)); ?></span><h3><a href="<?php echo esc_url(get_permalink($post_item)); ?>"><?php echo esc_html(get_the_title($post_item)); ?></a></h3><a class="rb-text-link" href="<?php echo esc_url(get_permalink($post_item)); ?>">Read guide</a></article><?php endforeach; ?></div></div></section><?php endif; ?>
<section class="rb-newsletter-section"><div class="rb-shell rb-newsletter rb-reveal"><div><span class="rb-kicker rb-kicker--light">JOIN THE RUWAH COMMUNITY</span><h2>Better skin knowledge, occasionally delivered.</h2><p>Product updates, routines and practical skincare education.</p></div><form action="<?php echo esc_url(ruwah_page_url('contact')); ?>" method="get"><label class="screen-reader-text" for="rb-newsletter-email">Email address</label><input id="rb-newsletter-email" type="email" name="email" placeholder="Your email address" required><button class="rb-button rb-button--champagne" type="submit">Continue</button><small>You’ll continue to our contact form with your email pre-filled.</small></form></div></section><?php get_footer(); ?>
