<?php
defined('ABSPATH') || exit;
$progress = function_exists('ruwah_shipping_progress') ? ruwah_shipping_progress() : ['remaining' => 0, 'percent' => 0];
$cart_count = function_exists('WC') && WC()->cart ? WC()->cart->get_cart_contents_count() : 0;
$logo_path = get_template_directory() . '/assets/ruwah-monogram.svg';
?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><script>document.documentElement.classList.add('rb-js');</script><?php wp_head(); ?></head><body <?php body_class(); ?>><?php wp_body_open(); ?>
<a class="rb-skip" href="#main-content"><?php esc_html_e('Skip to content', 'ruwah'); ?></a>
<div class="rb-announcement" aria-label="Store benefits"><span><?php esc_html_e('Free delivery over PKR 5,000', 'ruwah'); ?></span><i aria-hidden="true"></i><span><?php esc_html_e('Secure checkout', 'ruwah'); ?></span><i aria-hidden="true"></i><span><?php esc_html_e('Pakistan-wide delivery', 'ruwah'); ?></span></div>
<header class="rb-header" data-site-header><div class="rb-header-main rb-shell"><div class="rb-header-left"><button class="rb-icon-button rb-menu-button" type="button" data-menu-toggle aria-label="Open menu" aria-expanded="false"><svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button><button class="rb-icon-button rb-search-button" type="button" data-search-open aria-label="Search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg></button></div><a class="rb-header-brand" href="<?php echo esc_url(home_url('/')); ?>" aria-label="Ruwah Beauty home"><?php if (is_readable($logo_path)) { echo file_get_contents($logo_path); } else { echo '<strong>RUWAH BEAUTY</strong>'; } ?></a><div class="rb-header-tools"><a class="rb-track-order" href="<?php echo esc_url(ruwah_page_url('track-order')); ?>">Track Order</a><a class="rb-icon-button rb-account-link" href="<?php echo esc_url(ruwah_account_url()); ?>" aria-label="Account"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M5 21c0-4 3-7 7-7s7 3 7 7"/></svg></a><button class="rb-icon-button rb-header-cart" type="button" data-cart-open aria-label="Bag"><svg viewBox="0 0 24 24"><path d="M6 8h12l-1 13H7L6 8Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></svg><span class="rb-cart-count"><?php echo esc_html($cart_count); ?></span></button></div></div>
<nav class="rb-header-nav" data-menu aria-label="Primary navigation"><ul class="rb-nav-list rb-shell"><li><a href="<?php echo esc_url(ruwah_shop_url()); ?>">Shop</a></li><li><a href="<?php echo esc_url(add_query_arg('orderby', 'popularity', ruwah_shop_url())); ?>">Bestsellers</a></li><li><a href="<?php echo esc_url(add_query_arg('orderby', 'date', ruwah_shop_url())); ?>">New Arrivals</a></li><li><a href="<?php echo esc_url(home_url('/#routine')); ?>">Routine Finder</a></li><li><a href="<?php echo esc_url(ruwah_page_url('bundles')); ?>">Bundles</a></li><li><a href="<?php echo esc_url(ruwah_page_url('blog')); ?>">Glow Guide</a></li></ul></nav></header>
<div class="rb-overlay" data-overlay hidden></div>
<section class="rb-search" data-search hidden aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="rb-search-title"><div class="rb-search-card"><button class="rb-close" type="button" data-search-close aria-label="Close search">×</button><span class="rb-kicker">Search Ruwah Beauty</span><h2 id="rb-search-title">What are you looking for?</h2><form role="search" method="get" action="<?php echo esc_url(home_url('/')); ?>"><label class="screen-reader-text" for="rb-product-search">Search products</label><input id="rb-product-search" type="search" name="s" placeholder="Products, ingredients or concerns"><input type="hidden" name="post_type" value="product"><button class="rb-button" type="submit">Search</button></form></div></section>
<aside class="rb-cart-drawer" data-cart-drawer aria-hidden="true" aria-label="Shopping bag"><header><span class="rb-kicker">Your order</span><h2>Shopping bag</h2><button class="rb-close" type="button" data-cart-close aria-label="Close bag">×</button></header><div class="rb-cart-body widget_shopping_cart_content"><?php if (function_exists('woocommerce_mini_cart')) { woocommerce_mini_cart(); } ?></div><footer><p><?php echo $progress['remaining'] > 0 ? esc_html('Add PKR ' . number_format_i18n($progress['remaining']) . ' for free delivery') : esc_html__('You qualify for free delivery', 'ruwah'); ?></p><div class="rb-progress"><i style="width:<?php echo esc_attr($progress['percent']); ?>%"></i></div><a class="rb-button rb-button--dark" href="<?php echo esc_url(ruwah_cart_url()); ?>">View Bag &amp; Checkout</a></footer></aside><main id="main-content">
