<?php
/**
 * Dedicated Ruwah Beauty Privacy Policy template.
 */
defined('ABSPATH') || exit;

get_header();
?>
<div class="rwb-policy-page">
    <section class="rwb-policy-hero"><div class="rwb-policy-shell rwb-policy-shell--wide"><p class="rwb-policy-kicker">RUWAH BEAUTY · PRIVACY</p><h1>Privacy Policy</h1></div></section>
    <section class="rwb-policy-content"><div class="rwb-policy-shell rwb-policy-shell--wide"><article class="rwb-privacy-policy">
        <header class="rwb-policy-intro">
            <p class="rwb-policy-meta">Effective 27 August 2026 <span aria-hidden="true">·</span> Last updated 27 August 2026</p>
            <p class="rwb-policy-lead">Ruwah Beauty respects your privacy. This policy explains what information may be collected when you browse our store, create an account, contact us or place an order, why it is used, when it may be shared, and the choices available to you.</p>
            <p>Privacy email: <a href="mailto:rawahbeauty783@gmail.com">rawahbeauty783@gmail.com</a> · Customer support / WhatsApp: <a href="https://wa.me/923713923279">+92 371 3923279</a>. Our response target for customer and privacy enquiries is within 2 business days.</p>
        </header>

        <nav class="rwb-policy-index" aria-label="Privacy policy sections"><a href="#policy-collect">Information we collect</a><a href="#policy-use">How we use it</a><a href="#policy-cookies">Cookies</a><a href="#policy-sharing">Sharing</a><a href="#policy-retention">Retention</a><a href="#policy-rights">Your choices</a><a href="#policy-contact">Contact</a></nav>

        <section class="rwb-policy-section" id="policy-about"><span class="rwb-policy-number">01</span><div><h2>About this policy</h2><p>This policy applies to personal information handled through ruwahbeauty.com and the online-store functions operated for Ruwah Beauty in Pakistan. It does not control the privacy practices of independent websites or services that we do not operate.</p></div></section>

        <section class="rwb-policy-section" id="policy-collect"><span class="rwb-policy-number">02</span><div><h2>Information we collect</h2><p>The information we collect depends on how you use the store. It may include:</p><ul><li><strong>Identity and contact information</strong> such as your name, email address and phone number.</li><li><strong>Order and delivery information</strong> such as billing and shipping addresses, products ordered, quantities and order status.</li><li><strong>Account information</strong> when you create or use a customer account.</li><li><strong>Transaction information</strong> such as order value, currency and payment status. Current checkout is Cash on Delivery; online payment is not currently offered to customers.</li><li><strong>Communications</strong> including messages, support requests, reviews or other information you choose to send us.</li><li><strong>Technical and usage information</strong> such as IP address, browser/device information, session activity, security logs and cookie identifiers generated when you use the website.</li></ul></div></section>

        <section class="rwb-policy-section" id="policy-use"><span class="rwb-policy-number">03</span><div><h2>How we use your information</h2><p>We use personal information when reasonably necessary to operate the store and serve customers, including to:</p><ul><li>process, confirm, fulfil and support orders;</li><li>deliver purchases and communicate delivery or order updates;</li><li>operate customer accounts and respond to enquiries;</li><li>administer Cash on Delivery orders and, if online payments are introduced later, process payment status and refunds through the selected provider;</li><li>protect the website, customers and our business against fraud, abuse and security incidents;</li><li>maintain records needed for accounting, disputes and legal obligations;</li><li>improve website usability, products and customer service; and</li><li>send marketing communications where requested, with an unsubscribe option.</li></ul></div></section>

        <section class="rwb-policy-section" id="policy-cookies"><span class="rwb-policy-number">04</span><div><h2>Cookies and similar technologies</h2><p>Essential cookies support cart contents, checkout sessions, account login, security and site preferences. Ruwah Beauty does not require advertising cookies for the store to function. If analytics or advertising technologies are added, non-essential tracking should be used only in accordance with the consent controls and notices then provided.</p><p>You can control cookies through your browser settings, but blocking essential cookies may prevent the cart, account or checkout from working correctly.</p></div></section>

        <section class="rwb-policy-section" id="policy-sharing"><span class="rwb-policy-number">05</span><div><h2>Processors and service-provider categories</h2><p>We do not sell customer personal information. Information may be shared where reasonably necessary with service providers used to operate the store, including:</p><ul><li><strong>WordPress and WooCommerce</strong> technology used to run the website, account, cart and ordering functions;</li><li><strong>Hostinger</strong> and related hosting, cache, security and infrastructure services used by the website;</li><li>courier and logistics providers used to deliver customer orders;</li><li>email and customer-support services used to receive or respond to enquiries and order communications;</li><li>security, anti-fraud, backup or technical-support providers where used;</li><li>professional advisers; and</li><li>government, regulatory or law-enforcement authorities when disclosure is required by applicable law or valid legal process.</li></ul></div></section>

        <section class="rwb-policy-section" id="policy-payments"><span class="rwb-policy-number">06</span><div><h2>Checkout and payments</h2><p>Ruwah Beauty currently accepts <strong>Cash on Delivery only</strong>. No live online-payment gateway is presented to customers at checkout. If online payments are introduced later, this policy and checkout disclosures will be updated to identify the relevant payment-processing arrangement before customers are asked to use it.</p><p>We retain order value, payment method/status and fulfilment records required to administer the purchase, support customers and maintain business records.</p></div></section>

        <section class="rwb-policy-section" id="policy-retention"><span class="rwb-policy-number">07</span><div><h2>Retention targets</h2><p>Our working retention targets are designed to keep information only as long as reasonably necessary:</p><ul><li><strong>Order, invoice and transaction records:</strong> normally up to 7 years where needed for accounting, tax, disputes or legal obligations.</li><li><strong>Customer-support and return/refund correspondence:</strong> normally up to 24 months after the matter is closed, unless it must be retained with an order or dispute record.</li><li><strong>Routine technical/security logs:</strong> normally up to 90 days unless a security incident, fraud investigation or legal need requires longer retention.</li><li><strong>Marketing subscription information:</strong> until you unsubscribe or the list is retired; suppression records may be kept to respect an opt-out.</li></ul><p>These periods may be shortened where information is no longer needed or extended where law, accounting, fraud prevention, security or an active dispute requires it.</p></div></section>

        <section class="rwb-policy-section" id="policy-rights"><span class="rwb-policy-number">08</span><div><h2>Your choices and privacy rights</h2><p>Subject to applicable law and legal exceptions, you may ask us to help you access, correct or delete personal information associated with you. You may also ask questions about how your information is used.</p><p>Marketing emails should include an unsubscribe method where applicable. You may also email <a href="mailto:rawahbeauty783@gmail.com">rawahbeauty783@gmail.com</a> and ask to stop marketing messages. Some records cannot be deleted immediately where retention is required for completed orders, accounting, fraud prevention, disputes, security or legal obligations.</p></div></section>

        <section class="rwb-policy-section" id="policy-security"><span class="rwb-policy-number">09</span><div><h2>Security</h2><p>We use reasonable administrative and technical measures intended to protect information handled through the website, including access controls, hosted security features, HTTPS and platform security practices. No internet transmission or storage system can be guaranteed completely secure, so customers should also protect account credentials and never share passwords or one-time verification codes.</p></div></section>

        <section class="rwb-policy-section" id="policy-children"><span class="rwb-policy-number">10</span><div><h2>Children’s privacy</h2><p>Our online store is intended for customers able to make purchases under applicable law. We do not knowingly seek to collect personal information from children in circumstances where parental or guardian consent would be legally required.</p></div></section>

        <section class="rwb-policy-section" id="policy-international"><span class="rwb-policy-number">11</span><div><h2>International processing</h2><p>Hosting, email, security or other technology providers may store or process information on infrastructure located outside Pakistan. Where this occurs, information may be subject to the laws of the location in which it is processed. We use providers for operational purposes and limit sharing to information reasonably required for the service.</p></div></section>

        <section class="rwb-policy-section" id="policy-complaints"><span class="rwb-policy-number">12</span><div><h2>Questions and complaints</h2><p>Send a privacy question or complaint to <a href="mailto:rawahbeauty783@gmail.com">rawahbeauty783@gmail.com</a> with enough information to identify the relevant account, order or communication. Our target is to acknowledge the request within 2 business days and resolve or provide a substantive update as soon as reasonably possible. If a matter cannot be resolved directly, you may pursue any complaint or remedy available to you under applicable law.</p></div></section>

        <section class="rwb-policy-section" id="policy-updates"><span class="rwb-policy-number">13</span><div><h2>Changes to this policy</h2><p>We may update this policy when our services, technology or legal obligations change. The current version will be posted on this page with a revised “Last updated” date. Material changes may also be communicated through the website when appropriate.</p></div></section>

        <section class="rwb-policy-section rwb-policy-contact" id="policy-contact"><span class="rwb-policy-number">14</span><div><h2>Contact us about privacy</h2><p><strong>Ruwah Beauty</strong><br>Pakistan · Online skincare</p><p><strong>Privacy email:</strong> <a href="mailto:rawahbeauty783@gmail.com">rawahbeauty783@gmail.com</a><br><strong>Customer support / WhatsApp:</strong> <a href="https://wa.me/923713923279">+92 371 3923279</a><br><strong>Response target:</strong> within 2 business days.</p><p>You can also use our <a href="<?php echo esc_url(home_url('/contact/')); ?>">Contact Us</a> page.</p></div></section>
    </article></div></div></section>
</div>
<?php get_footer(); ?>