<?php
/**
 * Plugin Name: Ruwah Real Transparent Product Images
 * Description: Generates validated transparent PNG media attachments and assigns them as WooCommerce featured images.
 * Version: 2.4.0
 * Author: Ruwah Beauty
 * Requires PHP: 8.1
 */
defined('ABSPATH') || exit;
final class Ruwah_Product_Images {
    private const VERSION='2.4.0'; private const MAP='ruwah_rpi_map_v232'; private const STATUS='ruwah_rpi_status_v240'; private const ENGINE='ruwah_rpi_engine'; private const FAILURES='ruwah_rpi_failures_v240'; private const CONFLICT_STATE='ruwah_rpi_conflicts_before_v240';
    private const CONFLICTS=['nub-product-images-deep-purple-v4/nub-product-images-deep-purple-v4.php','ruwah-fresh-commerce-design/ruwah-fresh-commerce-design.php'];
    public static function boot():void{add_action('admin_menu',[self::class,'menu']);add_action('admin_post_ruwah_rpi_regenerate',[self::class,'regen']);add_action('admin_post_ruwah_rpi_restore',[self::class,'restore_action']);if(defined('WP_CLI')&&WP_CLI)add_action('cli_init',[self::class,'register_cli']);}
    public static function activate():void{delete_option(self::ENGINE);delete_option(self::FAILURES);}
    public static function register_cli():void{WP_CLI::add_command('ruwah product-images','Ruwah_Product_Images_CLI');}
    private static function disable_conflicts():void{require_once ABSPATH.'wp-admin/includes/plugin.php';foreach(self::CONFLICTS as$plugin){if(is_plugin_active($plugin))deactivate_plugins($plugin,true,false);}}
    public static function begin():array{require_once ABSPATH.'wp-admin/includes/plugin.php';$active=array_values(array_filter(self::CONFLICTS,'is_plugin_active'));update_option(self::CONFLICT_STATE,$active,false);self::disable_conflicts();delete_option(self::FAILURES);return['version'=>self::VERSION,'conflicts_before'=>$active,'updated_at'=>gmdate('c')];}
    private static function product_ids():array{return array_map('intval',get_posts(['post_type'=>'product','post_status'=>['publish','private','draft'],'numberposts'=>-1,'fields'=>'ids','orderby'=>'ID','order'=>'ASC']));}
    private static function previous_map():array{foreach([self::MAP,'ruwah_rpi_map_v231','ruwah_rpi_map_v23','ruwah_rpi_map_v22','ruwah_rpi_map_v21']as$option){$map=(array)get_option($option,[]);if($map)return$map;}return[];}
    public static function process_batch(int$limit=4,bool$force=false):array{
        @set_time_limit(300);@ini_set('memory_limit','1024M');require_once ABSPATH.'wp-admin/includes/image.php';require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';self::disable_conflicts();
        $limit=max(1,min(8,$limit));$ids=self::product_ids();$existing=self::previous_map();$map=(array)get_option(self::MAP,[]);$failures=(array)get_option(self::FAILURES,[]);$done=[];$handled=0;
        foreach($ids as$pid){if($handled>=$limit)break;$p=wc_get_product($pid);if(!$p){$failures[$pid]="$pid:product unavailable";$handled++;continue;}if(!$force&&!empty($map[$pid]['new_id'])&&get_post((int)$map[$pid]['new_id']))continue;if(!$force&&isset($failures[$pid]))continue;
            $current=(int)$p->get_image_id();$source_id=(int)($map[$pid]['original_id']??$existing[$pid]['original_id']??$current);if(!$source_id){$failures[$pid]="$pid:no source image";$handled++;continue;}
            $source=wp_get_original_image_path($source_id)?:get_attached_file($source_id);if(!$source||!is_readable($source)){$failures[$pid]="$pid:source unreadable";$handled++;continue;}
            $result=self::make_png($pid,$source_id,$source);if(is_wp_error($result)){$failures[$pid]="$pid:".$result->get_error_message();$handled++;continue;}
            $new_id=(int)$result['attachment_id'];update_post_meta($new_id,'_wp_attachment_image_alt',get_the_title($pid));unset($failures[$pid]);
            $map[$pid]=['original_id'=>$source_id,'new_id'=>$new_id,'opaque_fraction'=>$result['opaque_fraction'],'generated_at'=>gmdate('c')];$done[]=$pid;$handled++;}
        update_option(self::MAP,$map,false);update_option(self::FAILURES,$failures,false);$status=self::status();$status['processed_this_command']=count($done);$status['products']=$done;update_option(self::STATUS,$status,false);return$status;
    }
    private static function make_png(int$pid,int$source_id,string$source){
        if(!class_exists('Imagick'))return new WP_Error('imagick','Imagick unavailable');$up=wp_upload_dir();if(!empty($up['error']))return new WP_Error('upload',$up['error']);$dir=trailingslashit($up['basedir']).'ruwah-product-png';wp_mkdir_p($dir);$dest=trailingslashit($dir).'product-'.$pid.'-transparent-v232-'.time().'.png';
        try{$base=new Imagick($source);$base->setIteratorIndex(0);$base->setImageColorspace(Imagick::COLORSPACE_SRGB);$base->setImageAlphaChannel(Imagick::ALPHACHANNEL_SET);$base->thumbnailImage(1800,1800,true,true);$best=null;
            foreach([0.025,0.045,0.07,0.10]as$fuzz_ratio){$candidate=clone$base;$w=$candidate->getImageWidth();$h=$candidate->getImageHeight();$range=Imagick::getQuantumRange();$fuzz=(float)$range['quantumRangeLong']*$fuzz_ratio;foreach(self::edge_points($w,$h)as[$x,$y]){$target=$candidate->getImagePixelColor($x,$y);$candidate->floodFillPaintImage(new ImagickPixel('rgba(0,0,0,0)'),$fuzz,$target,$x,$y,false);}$candidate->trimImage(0);$candidate->setImagePage(0,0,0,0);$opaque=self::opaque_fraction($candidate);if($candidate->getImageWidth()>=240&&$candidate->getImageHeight()>=240&&$opaque>=0.05&&$opaque<=0.90){if($best)$best->clear();$best=$candidate;if($opaque<=0.72)break;}else{$candidate->clear();}}
            if(!$best){$base->clear();throw new RuntimeException('No valid transparent subject could be isolated');}$best->thumbnailImage(1060,1060,true,true);$canvas=new Imagick();$canvas->newImage(1200,1200,new ImagickPixel('rgba(0,0,0,0)'),'png32');$canvas->setImageAlphaChannel(Imagick::ALPHACHANNEL_SET);$canvas->compositeImage($best,Imagick::COMPOSITE_OVER,(int)((1200-$best->getImageWidth())/2),(int)((1200-$best->getImageHeight())/2));$canvas->setImageFormat('png32');$canvas->setImageCompressionQuality(98);if(!$canvas->writeImage($dest))throw new RuntimeException('PNG write failed');$base->clear();$best->clear();$canvas->clear();
        }catch(Throwable$e){@unlink($dest);return new WP_Error('generation',$e->getMessage());}
        $valid=self::validate_png($dest);if(is_wp_error($valid)){@unlink($dest);return$valid;}$attachment=wp_insert_attachment(['post_mime_type'=>'image/png','post_title'=>get_the_title($pid).' transparent PNG','post_status'=>'inherit','post_parent'=>$pid],$dest,$pid,true);if(is_wp_error($attachment)){@unlink($dest);return$attachment;}$meta=wp_generate_attachment_metadata((int)$attachment,$dest);wp_update_attachment_metadata((int)$attachment,$meta);update_post_meta((int)$attachment,'_wp_attachment_image_alt',get_the_title($pid));return['attachment_id'=>(int)$attachment,'opaque_fraction'=>$valid['opaque_fraction']];}
    private static function edge_points(int$w,int$h):array{$points=[];foreach([0,0.2,0.4,0.6,0.8,1]as$r){$x=min($w-1,max(0,(int)round(($w-1)*$r)));$y=min($h-1,max(0,(int)round(($h-1)*$r)));$points[]=[$x,0];$points[]=[$x,$h-1];$points[]=[0,$y];$points[]=[$w-1,$y];}return array_values(array_unique($points,SORT_REGULAR));}
    private static function opaque_fraction(Imagick$image):float{$range=Imagick::getQuantumRange();$stats=$image->getImageChannelMean(Imagick::CHANNEL_ALPHA);$mean=is_array($stats)?(float)($stats['mean']??0):0;return$range['quantumRangeLong']>0?$mean/(float)$range['quantumRangeLong']:0;}
    private static function validate_png(string$file){$info=@getimagesize($file);if(!$info||($info['mime']??'')!=='image/png'||($info[0]??0)!==1200||($info[1]??0)!==1200)return new WP_Error('invalid','PNG dimensions or MIME invalid');if((int)@filesize($file)<25000)return new WP_Error('blank','PNG file too small');try{$im=new Imagick($file);$im->setImageAlphaChannel(Imagick::ALPHACHANNEL_SET);$opaque=self::opaque_fraction($im);$im->clear();}catch(Throwable$e){return new WP_Error('alpha',$e->getMessage());}if($opaque<0.05)return new WP_Error('blank','Too little visible product content');if($opaque>0.92)return new WP_Error('opaque','No meaningful transparency');return['opaque_fraction'=>round($opaque,4)];}
    private static function active_conflicts():array{require_once ABSPATH.'wp-admin/includes/plugin.php';return array_values(array_filter(self::CONFLICTS,'is_plugin_active'));}
    public static function status():array{$ids=self::product_ids();$map=(array)get_option(self::MAP,[]);$failures=(array)get_option(self::FAILURES,[]);$generated=0;$applied=0;foreach($ids as$pid){$p=wc_get_product($pid);$new=(int)($map[$pid]['new_id']??0);if($new&&get_post($new)&&get_post_mime_type($new)==='image/png'){$generated++;if($p&&(int)$p->get_image_id()===$new)$applied++;}}return['version'=>self::VERSION,'total_products'=>count($ids),'generated'=>$generated,'applied'=>$applied,'generated_complete'=>count($ids)>0&&$generated===count($ids),'complete'=>count($ids)>0&&$applied===count($ids),'errors'=>array_values($failures),'conflicts_active'=>self::active_conflicts(),'updated_at'=>gmdate('c')];}
    public static function retry_failures():void{delete_option(self::FAILURES);}
    public static function apply(){$status=self::status();if(!$status['generated_complete'])return new WP_Error('incomplete','Not all product PNGs are staged');$map=(array)get_option(self::MAP,[]);$snapshot=[];try{foreach(self::product_ids()as$pid){$p=wc_get_product($pid);$new=(int)($map[$pid]['new_id']??0);if(!$p||!$new||!get_post($new)||get_post_mime_type($new)!=='image/png')throw new RuntimeException("Product $pid has no valid staged PNG");$snapshot[$pid]=(int)$p->get_image_id();}foreach(self::product_ids()as$pid){$p=wc_get_product($pid);$p->set_image_id((int)$map[$pid]['new_id']);$p->save();}update_option(self::ENGINE,self::VERSION,false);$status=self::status();update_option(self::STATUS,$status,false);return$status;}catch(Throwable$e){foreach($snapshot as$pid=>$image_id){$p=wc_get_product((int)$pid);if($p){$p->set_image_id((int)$image_id);$p->save();}}return new WP_Error('apply_failed',$e->getMessage());}}
    public static function restore():array{$map=(array)get_option(self::MAP,self::previous_map());$n=0;foreach($map as$pid=>$row){$p=wc_get_product((int)$pid);$id=(int)($row['original_id']??0);if($p&&$id&&get_post($id)){$p->set_image_id($id);$p->save();$n++;}}require_once ABSPATH.'wp-admin/includes/plugin.php';$before=(array)get_option(self::CONFLICT_STATE,[]);$reactivated=[];foreach($before as$plugin){$activation=activate_plugin($plugin,'',false,true);if(!is_wp_error($activation))$reactivated[]=$plugin;}delete_option(self::CONFLICT_STATE);delete_option(self::ENGINE);$result=self::status();$result['restored']=$n;$result['conflicts_expected']=count($before);$result['conflicts_reactivated']=$reactivated;update_option(self::STATUS,$result,false);return$result;}
    public static function menu():void{add_submenu_page('woocommerce','Ruwah Product PNGs','Product PNGs','manage_woocommerce','ruwah-product-pngs',[self::class,'page']);}
    public static function page():void{if(!current_user_can('manage_woocommerce'))return;$s=(array)get_option(self::STATUS,[]);$m=(array)get_option(self::MAP,[]);echo'<div class="wrap"><h1>Ruwah Product PNGs</h1><p>Mapped: <strong>'.esc_html((string)count($m)).'</strong></p><pre>'.esc_html(wp_json_encode($s,JSON_PRETTY_PRINT)).'</pre><p><a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=ruwah_rpi_regenerate'),'ruwah_rpi_regenerate')).'">Regenerate & Apply</a> <a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=ruwah_rpi_restore'),'ruwah_rpi_restore')).'">Restore Originals</a></p></div>';}
    public static function regen():void{if(!current_user_can('manage_woocommerce'))wp_die('Not allowed');check_admin_referer('ruwah_rpi_regenerate');self::begin();delete_option(self::ENGINE);$status=self::process_batch(8,true);if($status['generated_complete'])self::apply();wp_safe_redirect(admin_url('admin.php?page=ruwah-product-pngs'));exit;}
    public static function restore_action():void{if(!current_user_can('manage_woocommerce'))wp_die('Not allowed');check_admin_referer('ruwah_rpi_restore');self::restore();wp_safe_redirect(admin_url('admin.php?page=ruwah-product-pngs'));exit;}
}
final class Ruwah_Product_Images_CLI{
    public function begin(array$args,array$assoc):void{WP_CLI::success(wp_json_encode(Ruwah_Product_Images::begin()));}
    public function stage(array$args,array$assoc):void{$batch=max(1,min(8,(int)($assoc['batch-size']??2)));if(isset($assoc['retry-failed']))Ruwah_Product_Images::retry_failures();$status=Ruwah_Product_Images::process_batch($batch,false);WP_CLI::log(wp_json_encode($status));}
    public function apply(array$args,array$assoc):void{$status=Ruwah_Product_Images::apply();if(is_wp_error($status))WP_CLI::error($status->get_error_message());WP_CLI::success(wp_json_encode($status));}
    public function status(array$args,array$assoc):void{$status=Ruwah_Product_Images::status();WP_CLI::log(wp_json_encode($status));if(isset($assoc['require-complete'])&&!$status['complete'])WP_CLI::error('Product image migration is incomplete');}
    public function restore(array$args,array$assoc):void{$status=Ruwah_Product_Images::restore();if(count($status['conflicts_reactivated'])!==$status['conflicts_expected'])WP_CLI::error(wp_json_encode($status));WP_CLI::success(wp_json_encode($status));}
}
register_activation_hook(__FILE__,[Ruwah_Product_Images::class,'activate']);Ruwah_Product_Images::boot();
