<?php
/**
 * Plugin Name: Ruwah Real Transparent Product Images
 * Description: Generates validated transparent PNG media attachments and assigns them as WooCommerce featured images.
 * Version: 2.3.1
 * Author: Ruwah Beauty
 * Requires PHP: 8.1
 */
defined('ABSPATH') || exit;
final class Ruwah_Product_Images {
    private const VERSION='2.3.1'; private const MAP='ruwah_rpi_map_v231'; private const STATUS='ruwah_rpi_status_v231'; private const ENGINE='ruwah_rpi_engine';
    private const CONFLICTS=['nub-product-images-deep-purple-v4/nub-product-images-deep-purple-v4.php','ruwah-fresh-commerce-design/ruwah-fresh-commerce-design.php'];
    public static function boot():void{add_action('plugins_loaded',[self::class,'migrate'],40);add_action('admin_menu',[self::class,'menu']);add_action('admin_post_ruwah_rpi_regenerate',[self::class,'regen']);add_action('admin_post_ruwah_rpi_restore',[self::class,'restore_action']);}
    public static function activate():void{self::disable_conflicts();if(class_exists('WooCommerce'))self::process_batch(8,true);}
    public static function migrate():void{if(!class_exists('WooCommerce')||get_option(self::ENGINE)===self::VERSION)return;self::disable_conflicts();self::process_batch(4,false);}
    private static function disable_conflicts():void{require_once ABSPATH.'wp-admin/includes/plugin.php';foreach(self::CONFLICTS as$plugin){if(is_plugin_active($plugin))deactivate_plugins($plugin,true,false);}}
    private static function product_ids():array{return array_map('intval',get_posts(['post_type'=>'product','post_status'=>['publish','private','draft'],'numberposts'=>-1,'fields'=>'ids','orderby'=>'ID','order'=>'ASC']));}
    private static function previous_map():array{foreach([self::MAP,'ruwah_rpi_map_v23','ruwah_rpi_map_v22','ruwah_rpi_map_v21']as$option){$map=(array)get_option($option,[]);if($map)return$map;}return[];}
    public static function process_batch(int$limit=4,bool$force=false):array{
        @set_time_limit(300);@ini_set('memory_limit','1024M');require_once ABSPATH.'wp-admin/includes/image.php';require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';self::disable_conflicts();
        $ids=self::product_ids();$existing=self::previous_map();$map=(array)get_option(self::MAP,[]);$done=[];$errors=[];$handled=0;
        foreach($ids as$pid){if($handled>=$limit)break;$p=wc_get_product($pid);if(!$p){$errors[]="$pid:product unavailable";continue;}if(!$force&&!empty($map[$pid]['new_id'])&&(int)$p->get_image_id()===(int)$map[$pid]['new_id'])continue;
            $current=(int)$p->get_image_id();$source_id=(int)($map[$pid]['original_id']??$existing[$pid]['original_id']??$current);if(!$source_id){$errors[]="$pid:no source image";$handled++;continue;}
            $source=wp_get_original_image_path($source_id)?:get_attached_file($source_id);if(!$source||!is_readable($source)){$errors[]="$pid:source unreadable";$handled++;continue;}
            $result=self::make_png($pid,$source_id,$source);if(is_wp_error($result)){$errors[]="$pid:".$result->get_error_message();$handled++;continue;}
            $new_id=(int)$result['attachment_id'];$p->set_image_id($new_id);$p->save();update_post_meta($new_id,'_wp_attachment_image_alt',get_the_title($pid));
            $map[$pid]=['original_id'=>$source_id,'new_id'=>$new_id,'opaque_fraction'=>$result['opaque_fraction'],'generated_at'=>gmdate('c')];$done[]=$pid;$handled++;}
        update_option(self::MAP,$map,false);$complete=true;foreach($ids as$pid){$p=wc_get_product($pid);if(!$p||empty($map[$pid]['new_id'])||(int)$p->get_image_id()!==(int)$map[$pid]['new_id']){$complete=false;break;}}
        if($complete&&count($map)>=count($ids))update_option(self::ENGINE,self::VERSION,false);
        $status=['version'=>self::VERSION,'total_products'=>count($ids),'processed_this_request'=>count($done),'mapped'=>count($map),'complete'=>$complete,'products'=>$done,'errors'=>$errors,'conflicts_active'=>array_values(array_filter(self::CONFLICTS,'is_plugin_active')),'updated_at'=>gmdate('c')];update_option(self::STATUS,$status,false);return$status;
    }
    private static function make_png(int$pid,int$source_id,string$source){
        if(!class_exists('Imagick'))return new WP_Error('imagick','Imagick unavailable');$up=wp_upload_dir();if(!empty($up['error']))return new WP_Error('upload',$up['error']);$dir=trailingslashit($up['basedir']).'ruwah-product-png';wp_mkdir_p($dir);$dest=trailingslashit($dir).'product-'.$pid.'-transparent-v231-'.time().'.png';
        try{$base=new Imagick($source);$base->setIteratorIndex(0);$base->setImageColorspace(Imagick::COLORSPACE_SRGB);$base->setImageAlphaChannel(Imagick::ALPHACHANNEL_SET);$base->thumbnailImage(1800,1800,true,true);$best=null;
            foreach([0.025,0.045,0.07,0.10]as$fuzz_ratio){$candidate=clone$base;$w=$candidate->getImageWidth();$h=$candidate->getImageHeight();$range=Imagick::getQuantumRange();$fuzz=(float)$range['quantumRangeLong']*$fuzz_ratio;foreach(self::edge_points($w,$h)as[$x,$y]){$target=$candidate->getImagePixelColor($x,$y);$candidate->floodFillPaintImage(new ImagickPixel('rgba(0,0,0,0)'),$fuzz,$target,$x,$y,false);}$candidate->trimImage(0);$candidate->setImagePage(0,0,0,0);$opaque=self::opaque_fraction($candidate);if($candidate->getImageWidth()>=240&&$candidate->getImageHeight()>=240&&$opaque>=0.05&&$opaque<=0.90){if($best)$best->clear();$best=$candidate;if($opaque<=0.72)break;}else{$candidate->clear();}}
            if(!$best){$base->clear();throw new RuntimeException('No valid transparent subject could be isolated');}$best->thumbnailImage(1060,1060,true,true);$canvas=new Imagick();$canvas->newImage(1200,1200,new ImagickPixel('rgba(0,0,0,0)'),'png32');$canvas->setImageAlphaChannel(Imagick::ALPHACHANNEL_SET);$canvas->compositeImage($best,Imagick::COMPOSITE_OVER,(int)((1200-$best->getImageWidth())/2),(int)((1200-$best->getImageHeight())/2));$canvas->setImageFormat('png32');$canvas->setImageCompressionQuality(98);if(!$canvas->writeImage($dest))throw new RuntimeException('PNG write failed');$base->clear();$best->clear();$canvas->clear();
        }catch(Throwable$e){@unlink($dest);return new WP_Error('generation',$e->getMessage());}
        $valid=self::validate_png($dest);if(is_wp_error($valid)){@unlink($dest);return$valid;}$attachment=wp_insert_attachment(['post_mime_type'=>'image/png','post_title'=>get_the_title($pid).' transparent PNG','post_status'=>'inherit','post_parent'=>$pid],$dest,$pid,true);if(is_wp_error($attachment)){@unlink($dest);return$attachment;}$meta=wp_generate_attachment_metadata((int)$attachment,$dest);wp_update_attachment_metadata((int)$attachment,$meta);update_post_meta((int)$attachment,'_wp_attachment_image_alt',get_the_title($pid));return['attachment_id'=>(int)$attachment,'opaque_fraction'=>$valid['opaque_fraction']];}
    private static function edge_points(int$w,int$h):array{$points=[];foreach([0,0.2,0.4,0.6,0.8,1]as$r){$x=min($w-1,max(0,(int)round(($w-1)*$r)));$y=min($h-1,max(0,(int)round(($h-1)*$r)));$points[]=[$x,0];$points[]=[$x,$h-1];$points[]=[0,$y];$points[]=[$w-1,$y];}return array_values(array_unique($points,SORT_REGULAR));}
    private static function opaque_fraction(Imagick$image):float{$range=Imagick::getQuantumRange();$stats=$image->getImageChannelMean(Imagick::CHANNEL_ALPHA);$mean=is_array($stats)?(float)($stats['mean']??0):0;return$range['quantumRangeLong']>0?$mean/(float)$range['quantumRangeLong']:0;}
    private static function validate_png(string$file){$info=@getimagesize($file);if(!$info||($info['mime']??'')!=='image/png'||($info[0]??0)!==1200||($info[1]??0)!==1200)return new WP_Error('invalid','PNG dimensions or MIME invalid');if((int)@filesize($file)<25000)return new WP_Error('blank','PNG file too small');try{$im=new Imagick($file);$im->setImageAlphaChannel(Imagick::ALPHACHANNEL_SET);$opaque=self::opaque_fraction($im);$im->clear();}catch(Throwable$e){return new WP_Error('alpha',$e->getMessage());}if($opaque<0.05)return new WP_Error('blank','Too little visible product content');if($opaque>0.92)return new WP_Error('opaque','No meaningful transparency');return['opaque_fraction'=>round($opaque,4)];}
    public static function restore():array{$map=(array)get_option(self::MAP,self::previous_map());$n=0;foreach($map as$pid=>$row){$p=wc_get_product((int)$pid);$id=(int)($row['original_id']??0);if($p&&$id&&get_post($id)){$p->set_image_id($id);$p->save();$n++;}}$result=['restored'=>$n,'updated_at'=>gmdate('c')];update_option(self::STATUS,$result,false);return$result;}
    public static function menu():void{add_submenu_page('woocommerce','Ruwah Product PNGs','Product PNGs','manage_woocommerce','ruwah-product-pngs',[self::class,'page']);}
    public static function page():void{if(!current_user_can('manage_woocommerce'))return;$s=(array)get_option(self::STATUS,[]);$m=(array)get_option(self::MAP,[]);echo'<div class="wrap"><h1>Ruwah Product PNGs</h1><p>Mapped: <strong>'.esc_html((string)count($m)).'</strong></p><pre>'.esc_html(wp_json_encode($s,JSON_PRETTY_PRINT)).'</pre><p><a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=ruwah_rpi_regenerate'),'ruwah_rpi_regenerate')).'">Regenerate & Apply</a> <a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=ruwah_rpi_restore'),'ruwah_rpi_restore')).'">Restore Originals</a></p></div>';}
    public static function regen():void{if(!current_user_can('manage_woocommerce'))wp_die('Not allowed');check_admin_referer('ruwah_rpi_regenerate');delete_option(self::ENGINE);self::process_batch(8,true);wp_safe_redirect(admin_url('admin.php?page=ruwah-product-pngs'));exit;}
    public static function restore_action():void{if(!current_user_can('manage_woocommerce'))wp_die('Not allowed');check_admin_referer('ruwah_rpi_restore');self::restore();wp_safe_redirect(admin_url('admin.php?page=ruwah-product-pngs'));exit;}
}
register_activation_hook(__FILE__,[Ruwah_Product_Images::class,'activate']);Ruwah_Product_Images::boot();
